### ISSUE TITLE
Add FT ePass2003Auto

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/webcrypto-local#201]
```
{
	"cards": [{
		"atr": "3b9f958131fe9f006646530501001171df000003900080",
		"name": "FT ePass2003Auto",
		"driver": "29a2bd60c4b841c686be68d2874c0c02"
	}],
	"drivers": [{
		"id": "29a2bd60c4b841c686be68d2874c0c02",
		"name": "OpenSC",
		"file": {
			"linux": "/usr/lib/opensc-pkcs11.so"
		}
	}]
}
```

**Comment by jcca** [comment]
Hi,
Can you add library path for windows?
**"windows": "%WINDIR/System32/opensc-pkcs11.dll"**

**Comment by rmhrisk** [comment]
@microshine can this be closed if @jcca confirms it works?

**Comment by rmhrisk** [comment]
@jcca can you restart fortify and see if this token is recognized?

**Comment by severo** [comment]
Be careful that https://github.com/PeculiarVentures/webcrypto-local/commit/2ed40596eed982e08fd8db402c18654a0ed0f4a4 includes local files that should have been ignored, I think.

**Comment by microshine** [comment]
@severo Thank you

**Comment by rmhrisk** [comment]
Added

**Comment by jcca** [comment]
It works too, I can see "Token not initialized or unknown card state. No slots found." but it is because OpenSC 0.17 have an issue with ePass2003Auto
https://github.com/OpenSC/OpenSC/issues/1115
