### ISSUE TITLE
Add support for Athena IDProtect Smart Card Logon Card

### ISSUE THREAD

**Issue by jcca** [PeculiarVentures/webcrypto-local#211]
ATR: 3B DC 18 FF 81 91 FE 1F C3 80 73 C8 21 13 66 01 0B 03 52 00 05 38
Token: Athena IDProtect Smart Card Logon Card

PKCS#11 library paths:

* GNU/Linux:
    /usr/lib/x86-athena/libASEP11.so
    /usr/lib/x64-athena/libASEP11.so
* Windows: C:\Windows\System32\asepkcs.dll
* OSX: /Library/Application Support/Athena/libASEP11.dylib

**Comment by rmhrisk** [comment]
@jcca In theory adding this entry to card.json will enable it to work, can you do that and confirm?

You will need to edit 
- OSX: `~/.fortify/card.json`
- Win: `/users/<user>/Fortify/card.json`

Put in these entries in the right sections:

```
{
	"cards": [{
		"atr": "3b9f958131fe9f006646530501001171df000003900080",
		"name": "Athena IDProtect Smart Card Logon Card",
		"driver": "3BDC18FF8191FE1FC38073C8211366010B0352000538"
	}],
	"drivers": [{
		"id": "29a2bd60c4b841c686be68d2874c0c02",
		"name": "Athena IDProtect",
		"file": {

			"linux": {
				"x86": "/usr/lib/x86-athena/libASEP11.so",
				"x64": "/usr/lib/x64-athena/libASEP11.so"
			},
			"osx": "/Library/Application Support/Athena/libASEP11.dylib",
			"windows": "%WINDIR/System32/asepkcs.dll"
		}
	}]
}
```

Restart Fortify and insert the card to see if its detected.

Let us know

**Comment by jcca** [comment]
With some changes it works
{
	"cards": [{
		"atr": "3BDC18FF8191FE1FC38073C8211366010B0352000538",
		"name": "Athena IDProtect Smart Card Logon Card",
		"driver": "29a2bd60c4b841c686be68d2874c0c02"
	}],
	"drivers": [{
		"id": "29a2bd60c4b841c686be68d2874c0c02",
		"name": "Athena IDProtect",
		"file": {

			"linux": {
				"x86": "/usr/lib/x86-athena/libASEP11.so",
				"x64": "/usr/lib/x64-athena/libASEP11.so"
			},
			"osx": "/Library/Application Support/Athena/libASEP11.dylib",
			"windows": "%WINDIR/System32/asepkcs.dll"
		}
	}]
}

**Comment by rmhrisk** [comment]
Yes, it seems I used the wrong ATR.

@microshine please add this to card.jws

**Comment by rmhrisk** [comment]
@jcca if you restart fortify this should now be pulled down to your machine.
