### ISSUE TITLE
How  to extract signature from certificate

### ISSUE THREAD

**Issue by MasakiMinamide** [PeculiarVentures/webcrypto-local#224]
Is it possible to extract signature from certificate? In the below code, cert is missing signature.
Also, I want to get hash of certification, how can I get certification file as it is stored in SmartCard?

```
const crypto = await ws.getCrypto(providerId);
let cert = await crypto.certStorage.getItem(certIndex);
```

**Comment by microshine** [comment]
You can export a certificate from the Smart Card.

### Get SHA-1 thumbprint of certificate
```js
const crypto = await ws.getCrypto(providerId);
const cert = await crypto.certStorage.getItem(certIndex);
cons raw = await crypto.certStorage.exportCert("raw", cert);

const thumbprint = await crypto.subtle.digest("SHA-1", raw);
```

For getting extensions or signature from the certificate use any npm module which works with X509 certificates (eg [PKI.js](https://www.npmjs.com/package/pkijs))

**Comment by MasakiMinamide** [comment]
Thank you!
