### ISSUE TITLE
Cannot verify signature

### ISSUE THREAD

**Issue by MasakiMinamide** [PeculiarVentures/webcrypto-local#225]
I'm having a trouble in verification of signature.
My smartcard's private key algorithm name is `RSASSA-PKCS1-v1_5`, where matching public key algorithm name is `RSA-OAEP`. 
Calling `crypto.subtle.verify`, I get error that RSA-OAEP is not supported.  What should I do?

I dont think this is a problem in the key because sign-verify succeeds with pkcs11-tool and openssl.
```
$pkcs11-tool --sign -i hello.txt -o hello.sign
$openssl rsautl -verify -in hello.sign -pubin -inkey public-key.pem
>> hello, world!
```

**Comment by microshine** [comment]
`RSA-OAEP` algorithm can be used for `encrypt` and `decrypt` operations. You need to get you public key in the same `RSASSA-PKCS1-v1_5` algorithm which you used for signing.

You can do it in two ways:
  1. Export your public key to `spki` format and import it with the required algorithm
```js
const spki = await crypto.subtle.exportKey("spki", publicKey);
const rsassaPublicKey = await crypto.subtle.importKey("spki", spki, {name: "RSASSA-PKCS1-v1_5", hash: "SHA-256"}, true, ["verify"]);
```
  2. Get your public key from `keyStorage` with the required algorithm
```js
const rsassaPublicKey = await crypto.keyStorage.getItem(pubKeyIndex, {name: "RSASSA-PKCS1-v1_5", hash: "SHA-256"}, ["verify"]);
```

**Comment by MasakiMinamide** [comment]
It worked! Thanks for your support!
