### ISSUE TITLE
How to verify certificate

### ISSUE THREAD

**Issue by MasakiMinamide** [PeculiarVentures/webcrypto-local#226]
Does `verify` also support verification of x509 CA certificate?
If not, how can I achieve this?

With openssl, verification can be done by this command:
`$openssl verify -verbose -CAfile authCA.crt authca01.crt `

**Comment by microshine** [comment]
Use [CertificateChainValidationEngine PKI.js](https://github.com/PeculiarVentures/PKI.js/blob/master/src/CertificateChainValidationEngine.js) to do it. `webcrypto-local` has [additional methods](https://github.com/PeculiarVentures/webcrypto-local/blob/32b6ba6e8b77e1f375af5c577d6cc6a996f96b85/packages/client/src/cert_storage.ts#L219-L270) to get a certificate chain, CRL, or OCSP
