### ISSUE TITLE
E6 module error: protobuf is not defined

### ISSUE THREAD

**Issue by MasakiMinamide** [PeculiarVentures/webcrypto-local#231]
I want to use E6 module instead of getting js from urls.

import WebcryptoSocket from '@webcrypto-local/client';
const ws = new WebcryptoSocket.SocketProvider({
      storage: await WebcryptoSocket.BrowserStorage.create(),
});

gives me protobuf is not defined error. What should I do?

<img width="922" alt="Screen Shot 2020-01-28 at 14 31 23" src="https://user-images.githubusercontent.com/28042665/73238048-df1b3680-41da-11ea-82a2-59022a4860e8.png">

**Comment by rmhrisk** [comment]
Include protobuf package?


<script src="https://cdn.rawgit.com/dcodeIO/protobuf.js/6.8.0/dist/protobuf.min.js" defer></script>

https://www.npmjs.com/package/protobufjs

**Comment by MasakiMinamide** [comment]
Didn't notice. Thank you!
