### ISSUE TITLE
Issue related to Socket connection is not open

### ISSUE THREAD

**Issue by rossinicolas** [PeculiarVentures/webcrypto-local#257]
Dear @donskov , i'm using a PeculiarFortifyCertificates react component in my application to select a certificate that i will use to sign a pdf file.
Everything it's ok the firs time thay i used, but, if i choose another file to sign without press F5 key i have an error.
After debug the code between a lot of line, i saw that the error is in the line 5077 file webcrypto-socket

` Client.prototype.checkSocketState = function () {
            if (this.state !== SocketCryptoState.open) {
                **throw new Error("Socket connection is not open");**
            }
        };`

because "this.state" has the the value 3 (close).

Could you tell me how can i use that component without refresh the page in the browser?.
TIA.

**Comment by donskov** [comment]
Hello @rossinicolas,

Thank you for using our products.
In order to help find out what happened we need additional information:
1. How much time spend between files choices?
2. Do you close `PeculiarFortifyCertificates` after the file choose?
3. Send your fortify.log (if you can) to my mail dmitriy.donskov@peculiarventures.com.

Best regards,
Dmitriy.

**Comment by rossinicolas** [comment]
> Hello @rossinicolas,
> 
> Thank you for using our products.
> In order to help find out what happened we need additional information:
> 
>     1. How much time spend between files choices?
> 
>     2. Do you close `PeculiarFortifyCertificates` after the file choose?
> 
>     3. Send your fortify.log (if you can) to my mail [dmitriy.donskov@peculiarventures.com](mailto:dmitriy.donskov@peculiarventures.com).
> 
> 
> Best regards,
> Dmitriy.


Hi @donskov , i will try answer you:
1. Really, short time, because i sign on file after other with at most a minute.
2. i'm using PeculiarFortifyCertificates from @peculiar/fortify-webcomponents-react, that's as React Component, so my app is render the component continually between each "Sign Event".
3. Where is the log file?

`import { PeculiarFortifyCertificates } from '@peculiar/fortify-webcomponents-react';
const DigitalSignature = (props: MyProps) => {

 const handlerContinue = async (e: CustomEvent<TContinueEvent>) => {
//do something to sign pdf file
}

return(
<PeculiarFortifyCertificates
          filters={{
            onlyWithPrivateKey: true,
            onlySmartcards:
              process.env.NEXT_PUBLIC_ONLYSMARTCARDS == 'true' ? true : false,
            keyUsage: ['digitalSignature'],
          }}
          hideFooter={true}
          onCancel={(e) => {}}
          onContinue={(e) => {
            handlerContinue(e);
          }}
        />)
}
export default DigitalSignature
`

**Comment by rossinicolas** [comment]
Thanks to @donskov . The issue was resolved using a unique name in SetEngine.

`setEngine(
 'newEngine', // <--- used unique name for each operation
provider,
new CryptoEngine({
name: '',
crypto: provider,
subtle: provider.subtle,
}),
;`

he was very helpful to solve the problem. Also, the web component has a Spanish Translation available in 
- @peculiar/fortify-webcomponents-react@0.2.34
- @peculiar/fortify-webcomponents@0.21.0
